#!/usr/bin/env python3
"""Build and rehearse synthetic continuity; cleans only its unique test resources."""
import argparse
from pathlib import Path
import secrets
import socket
import subprocess
import sys
import time
import uuid

import requests
from backup import backup, restore, docker, LABEL

ROOT = Path(__file__).resolve().parent


def run(*args):
    subprocess.run(list(args), check=True, cwd=ROOT)


def port():
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0))
        return sock.getsockname()[1]


def compose(envfile, *args):
    run('docker', 'compose', '--env-file', str(envfile), '-f', str(ROOT/'compose.yaml'), *args)


def wait_ready(url):
    for _ in range(60):
        try:
            if requests.get(url + '/hub/login', timeout=2).status_code == 200:
                return
        except requests.RequestException:
            pass
        time.sleep(1)
    raise RuntimeError('Hub did not become ready')


def cleanup(instance, envfile):
    # Unique names generated by this invocation, never a supplied deployment.
    ids = docker('ps', '-aq', '--filter', f'label={LABEL}={instance}').split()
    if ids:
        docker('rm', '-f', *ids)
    compose(envfile, 'down')
    for kind in ('network', 'volume'):
        ids = docker(kind, 'ls', '-q', '--filter', f'label={LABEL}={instance}').split()
        if ids:
            docker(kind, 'rm', *ids)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reuse-hub-image', help='reuse an already built Hub image instead of building both images')
    parser.add_argument('--course-image', default='educloud-python-r:2026-10-06')
    args = parser.parse_args()
    prefix = 'verify-' + uuid.uuid4().hex[:10]
    output = ROOT/'output'/prefix
    output.mkdir(parents=True, mode=0o700)
    password = secrets.token_urlsafe(32)
    envfiles = []
    origins = []
    instances = [prefix, prefix + '-restore']
    for instance in instances:
        envfile = output/(instance + '.env')
        listen = port()
        origin = f'http://127.0.0.1:{listen}'
        env = dict(WORKSPACE_INSTANCE=instance, WORKSPACE_IMAGE=args.course_image,
                   WORKSPACE_PORT=str(listen), WORKSPACE_PUBLIC_URL=origin,
                   WORKSPACE_AUTH_MODE='local-test', WORKSPACE_TEST_PASSWORD=password,
                   WORKSPACE_ENV_FILE=str(envfile))
        envfile.write_text(''.join(f'{k}={v}\n' for k,v in env.items()))
        envfile.chmod(0o600)
        envfiles.append(envfile)
        origins.append(origin)
    try:
        if args.reuse_hub_image:
            run('docker', 'tag', args.reuse_hub_image, prefix + '-hub:pilot')
        else:
            compose(envfiles[0], '--profile', 'build', 'build')
        run('docker', 'tag', prefix + '-hub:pilot', instances[1] + '-hub:pilot')
        compose(envfiles[0], 'up', '-d', 'hub')
        wait_ready(origins[0])
        run(sys.executable, str(ROOT/'smoke.py'), '--env-file', str(envfiles[0]))
        # Explicit stop/recreate through DockerSpawner, retaining both homes.
        run(sys.executable, str(ROOT/'smoke.py'), '--env-file', str(envfiles[0]), '--restored')
        try:
            backup(prefix, output/'must-not-backup-live', args.course_image)
        except ValueError as exc:
            if 'stop every container' not in str(exc):
                raise
            print('Live backup correctly refused', flush=True)
        else:
            raise AssertionError('live backup unexpectedly accepted')
        compose(envfiles[0], 'stop', 'hub')
        archive = output/'archive'
        backup(prefix, archive, args.course_image)
        for item in archive.glob('*.tar.gz'):
            if item.stat().st_mode & 0o777 != 0o600:
                raise AssertionError('archive permissions must be owner-only')
        restore(instances[1], archive, args.course_image)
        try:
            restore(instances[1], archive, args.course_image)
        except ValueError as exc:
            if 'refusing to overwrite' not in str(exc):
                raise
            print('Existing-volume overwrite correctly refused', flush=True)
        else:
            raise AssertionError('second restore unexpectedly accepted')
        compose(envfiles[1], 'up', '-d', 'hub')
        wait_ready(origins[1])
        run(sys.executable, str(ROOT/'smoke.py'), '--env-file', str(envfiles[1]), '--restored')
        (output/'PASS.txt').write_text('Synthetic kernels, isolation, restart and namespace recovery passed.\n')
        print(f'PASS: evidence and synthetic archive at {output}', flush=True)
    finally:
        for instance, envfile in zip(instances, envfiles):
            cleanup(instance, envfile)


if __name__ == '__main__':
    main()
